[package]
version = "0.1.4"
name = "blaise"
description = "A fast, local-first engine for GTFS transit data. Handles routing, fuzzy search, and geospatial queries without relying on external APIs."
authors = ["Vincent Brodin <vincent.brodin21@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/vincbro/blaise"
edition = "2024"
keywords = [
  "transit",
  "gtfs",
  "routing-engine",
  "raptor",
  "public-transport",
]

[[bench]]
name = "short"
harness = false

[[bench]]
name = "long"
harness = false


[dependencies]
ahash = "0.8.12"
chrono = "0.4.44"
criterion = "0.8.2"
dialoguer = {version = "0.12.0", features = ["fuzzy-select"] }
# gtfs-bin = "0.1.3"
gtfs-bin = { path = "../gtfs-bin" }
memmap2 = "0.9.10"
rayon = "1.11.0"
rustc-hash = "2.1.2"
smallvec = "1.15.1"
thiserror = "2.0.17"
tracing = "0.1.44"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true 

[profile.profiling]
inherits = "release"
debug = true
strip = false
